### PR TITLE
feat(angular) Add angular output

### PR DESCRIPTION
**Pull request by th0513663**
## Summary of the changes
This PR adds a stencilJs angularOutputTarget configuration and associated package. This allows Angular developers to import a native angular module as opposed to importing native web-components that require configuration changes that turn off a lot of helpful compiler features using CUSTOM_ELEMENTS_SCHEMA. This PR will greatly enhance developer experience for those using the IC-UI-Kit within angular.

Instead of using CUSTOM_ELEMENTS_SCHEMA and importing loaders, the developer can now simply install the @ic-ui-kit/angular and @ic-ui-kit/web-components packages and import the module as follows:

```
import { UkicModule } from "@ukic/angular/dist";

@NgModule({
  declarations: [],
  imports: [
    UkicModule,
  ]
})
export class AppModule { }
```

## Related issue
This PR will resolve the following 3 tickets:
https://github.com/mi6/ic-ui-kit/issues/776
https://github.com/mi6/ic-ui-kit/issues/850
https://github.com/mi6/ic-design-system/issues/499

### CODE REVIEW

**Review by GCHQ-Developer-530 — COMMENTED** [review]
Hi @th0513663, thanks for the contribution, this looks really good! 

Only one comment from me, please could remove the merge commits so that there's just the feat(angular) commit? 😊

**Comment by GCHQ-Developer-530** [comment]
Looks like it's failing our checks due to an audit issue. The fix for this is on develop, so should be easily fixed if you rebase off develop.

**Comment by th0513663** [comment]
@GCHQ-Developer-530 Done :)

**Comment by GCHQ-Developer-530** [comment]
Hi @th0513663, sorry due to our last release this now has merge conflicts, would you be able to fix please?

**Comment by MI6-255** [comment]
Apologies for the delay in coming back to you. We're keen to implement this issue if it's needed, however, we're holding off from merging into production as it'll require surrounding work such as new tests, code examples on the website, among many other smaller tasks. Please do bare with us and thank you so much for the contribution. In the meantime, I'll move the target branch to an Angular branch for when we make this move.

**Comment by MI6-255** [comment]
I'm going to close this PR based on the above comments and it going stale, please feel free to re-open it at a later stage if needed. We will also be able to use this code as the pre-work for when/if we make the transition

**Pull request closed without merging**
