### PR TITLE
Fix/2110 new filename

### LINKED ISSUE #2110: Rename lintstaged.json to js file with kebab-case
## Summary 
To have consistency across the codebase, make the lint staged a js file like here: https://github.com/webpack/webpack-cli/blob/master/lint-staged.config.js

## 💬 Description 
See above

## 💰 Use value 
N/A

## 📝 Acceptance Criteria  
N/A

## ✏ Designs 
N/A

## 🧾 Guidance 
N/A

## Additional info 
N/A

### PR DESCRIPTION
**Pull request by evenstensberg**
## Summary of the changes
Moves to a more choherent naming convention.

## Related issue
Fixes #2110 

### General 

- [x] Changes to docs package checked and committed.
- [x] All acceptance criteria reviewed and met. 

### Testing

- [x] Relevant unit tests and visual regression tests added. 
- [x] Visual testing against Figma component specification completed. 
- [x] Playground stories in React Storybook up to date, with any prop changes and additions addressed. 

### Accessibility 

- [x] Accessibility Insights FastPass performed.
- [x] A11y unit test added and yields no issues.
- [x] A11y plug-in on Storybook yields no issues. 
- [x] Manual screen reader testing performed using NVDA and VoiceOver. 
- [x] Manual keyboard testing for keyboard controls and logical focus order. 
- [x] Correct roles used and ARIA attributes used correctly where required. 
- [x] Logical heading structure is maintained, and the HTML elements used for headings can be changed to fit within the wider page structure. 

### Resize/zoom behaviour 

- [x] Page can be zoomed to 400% with no loss of content. 
- [x] Screen magnifier used with no issues. 
- [x] Text resized to 200% with no loss of content.
- [x] Text spacing increased as per the [WCAG 1.4.12 success criterion](https://www.w3.org/TR/WCAG21/#text-spacing) with no loss of content.

### System modes

- [x] Browser setting 'prefers reduced motion' tested. No animations or motion visible whilst this setting is on. 
- [x] Windows High Contrast mode tested with no loss of content.
- [x] System light and dark mode tested with no loss of content.
- [x] Browser support tested (Chrome, Safari, Firefox and Edge). 

### Testing content extremes

- [x] Min/max content examples tested with no loss of content or overflow. 
- [x] All prop combinations work without issue. 
- [x] Tested for FOUC (Flash of Unstyled Content) in both SSR (Server-Side Rendering) and SSG (Static Site Generation) settings.
- [x] Controlled and uncontrolled input components tested.

### CODE REVIEW

**Comment by GCHQ-Developer-112** [comment]
Hi @evenstensberg, thank you for your contributions! Please consider picking up a ticket from our backlog for future contributions.[ Issues that labelled are "Good first issue" and have the status: "Ready for dev" ](https://github.com/orgs/mi6/projects/2/views/1?filterQuery=-is%3Apr+label%3A%22good+first+issue%22)  are a good place to start. These are tickets that have gone through our triage process and have been assessed as work we'd like to do

**Comment by evenstensberg** [comment]
Okay 👍🏾

**Comment by GCHQ-Developer-112** [comment]
Closing as this change is not needed

**Comment by evenstensberg** [comment]
@GCHQ-Developer-112 The reason for these small PRs is that I had some nitpicks that might improve the project such as adding nvmrc etc. It's optional to merge them, meaning the commits are not significant for the project, but sometimes nice to implement.

**Comment by GCHQ-Developer-112** [comment]
@evenstensberg we appreciate external contributions and appreciate the value these changes can bring 😀 
Where there are changes, such as the file name change in this PR, that don't offer much value, we're more likely to close them. PRs such as the cspell PR on the other hand are useful as it's clear so spelling mistakes have been missed during our review process. 

To prevent time being spent on an issue that we may decide is not the direction we want to go in, I advise waiting for the issue you've opened to be triaged. Through the triage process, we decide whether we think the work is of value or not. If it's work we plan to do, its status will be changed to design to do, in refinement or ready for dev. If not, the issue will be closed. This was the reason I directed you to our [issues that labelled are "Good first issue" and have the status: "Ready for dev"](https://github.com/orgs/mi6/projects/2/views/1?filterQuery=-is%3Apr+label%3A%22good+first+issue%22)

**Comment by evenstensberg** [comment]
Gotcha. Will fix the cspell PR then have a look at the kanban board.

**Pull request closed without merging**
