### PR TITLE
Toast component

### PR DESCRIPTION
**Pull request by GCHQ-Developer-741**
## Summary of the changes
Cloned PR for toast due to rebasing issue on previous PR.

## Related issue
#30 

## Checklist
- [x] I have added relevant unit and visual regression tests.
- [x] I have manually accessibility tested any changes, if relevant.
- [x] I have ensured any changes match the Figma component library.

### CODE REVIEW

**Comment by GCHQ-Developer-741** [comment]
On the whole, it looks great. I had a couple of questions however:

With regards to focus, when a toast is displayed we trap focus on the toast element, but you can still use pointer to move focus to something on the base layer. I'm not sure that trapping focus is correct. As the toast doesn't behave modally (you can still interact with the background layer) I would imagine focus would continue to move to other elements on the page. The toast would be injected into the focus order immediately after the triggering element.

The aria dialog spec says this:

"Dialogs can be modal or non-modal. When a modal dialog appears on the screen, it's not possible to interact with any page content outside the dialog. In other words, the main application UI or page content is considered to be temporarily disabled as long as the modal dialog is showing. For non-modal dialogs it is still possible to interact with content outside of the dialog while the dialog is showing. Note that for non-modal dialogs there will have to be a global keyboard shortcut that allows focus to be moved between opened dialogs and the main page."
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/dialog_role

When a non-modal dialog is displayed, we should move focus to the first focusable element within, but should we also allow focus to move out of the non-modal dialog? Could we provide a mechanism (landmark?) for moving between base layer content and dialog content?

Another option would be to automatically dismiss the non-modal dialog (toast) when a user interacts with an element outside of the toast. See this example from deque univesity. 
https://dequeuniversity.com/library/aria/tooltip-dialog

Inconveniently, although the WAI-ARIA authoring practices repeatedly reference non-modal dialogs being an option, there doesn't seem to be specific practices around them.
https://w3c.github.io/aria-practices/#dialog_modal

I think we should double check with the a11y team on what they suggest the best approach here is.

**Comment by GCHQ-Developer-741** [comment]
Screenshot from 2023-02-22 16-35-58
Screenshot from 2023-02-22 16-35-51

**Review by GCHQ-Developer-530 — COMMENTED** [review]
Looks like the commit messages might need changing as currently the changelog won't describe that there's a new toast component, it'll look more like different issues have been fixed.

**Comment by GCHQ-Developer-741** [comment]
> Similar to @ad9242's [comment for the dialogs PR](https://github.com/mi6/ic-ui-kit/pull/438#issuecomment-1443964805), I'm not sure the visual tests are adding much value. Might be worth investigating if there's a way to show the toast in the visual tests or remove them?

Have removed them from the loki tests

**Comment by GCHQ-Developer-741** [comment]
> Looks like the commit messages might need changing as currently the changelog won't describe that there's a new toast component, it'll look more like different issues have been fixed.

Sorted 😌

**Review by MI6-451 — APPROVED** [review]

**Review by DBD324 — COMMENTED** [review]
For the neutral status version, it would be good to make it so that if a user forgets to specify an icon, no icon is displayed rather than the default. Worried the default ? icon being used as a placeholder could be confusing at it symbolizes a question. If a user doesn't override the icon, can we hide it and have the text move over to fill the width of the toast?

**Comment by DBD324** [comment]
On the back of the a11y testing session conducted last week, did we manage to get the auto-dismiss toast contents to be announced as a live region? It wasn't doing this when tested, but not sure if this was a browser issue.

**Comment by GCHQ-Developer-741** [comment]
> For the neutral status version, it would be good to make it so that if a user forgets to specify an icon, no icon is displayed rather than the default. Worried the default ? icon being used as a placeholder could be confusing at it symbolizes a question. If a user doesn't override the icon, can we hide it and have the text move over to fill the width of the toast?

Addressed

**Review by DBD324 — DISMISSED** [review]

**Review by MI6-451 — APPROVED** [review]

**Review by DBD324 — APPROVED** [review]

**Review by MI6-451 — APPROVED** [review]

**Pull request merged**
