### PR TITLE
chore(root): fix cspell flags, add cpsell to ci and precommit hook

### PR DESCRIPTION
**Pull request by evenstensberg**
## Summary of the changes
Adds Cspell to the static analysis stage of the CI.

## Related issue

- #2237

### General 

- [x] Changes to docs package checked and committed.
- [x] All acceptance criteria reviewed and met. 

### Testing

- [x] Relevant unit tests and visual regression tests added. 
- [x] Visual testing against Figma component specification completed. 
- [x] Playground stories in React Storybook up to date, with any prop changes and additions addressed. 
- [x] Compare performance of modified components against develop using Performance addon in React Storybook.

### Accessibility 

- [x] Accessibility Insights FastPass performed.
- [x] A11y unit test added and yields no issues.
- [x] A11y plug-in on Storybook yields no issues. 
- [x] Manual screen reader testing performed using NVDA and VoiceOver. 
- [x] Manual keyboard testing for keyboard controls and logical focus order. 
- [x] Correct roles used and ARIA attributes used correctly where required. 
- [x] Logical heading structure is maintained, and the HTML elements used for headings can be changed to fit within the wider page structure. 

### Resize/zoom behaviour 

- [x] Page can be zoomed to 400% with no loss of content. 
- [x] Screen magnifier used with no issues. 
- [x] Text resized to 200% with no loss of content.
- [x] Text spacing increased as per the [WCAG 1.4.12 success criterion](https://www.w3.org/TR/WCAG21/#text-spacing) with no loss of content.

### System modes

- [x] Browser setting 'prefers reduced motion' tested. No animations or motion visible whilst this setting is on. 
- [x] Windows High Contrast mode tested with no loss of content.
- [x] System light and dark mode tested with no loss of content.
- [x] Browser support tested (Chrome, Safari, Firefox and Edge). 

### Testing content extremes

- [x] Min/max content examples tested with no loss of content or overflow. 
- [x] All prop combinations work without issue. 
- [x] Tested for FOUC (Flash of Unstyled Content) in both SSR (Server-Side Rendering) and SSG (Static Site Generation) settings.
- [x] Controlled and uncontrolled input components tested.

### CODE REVIEW

**Review by GCHQ-Developer-530 — DISMISSED** [review]

**Review by GCHQ-Developer-112 — CHANGES_REQUESTED** [review]
Please add cspell to the husky [`pre-commit`](https://github.com/mi6/ic-ui-kit/blob/develop/.husky/pre-commit). This means that any spelling errors can be caught locally before any work is pushed

**Review by GCHQ-Developer-530 — APPROVED** [review]

**Comment by GCHQ-Developer-112** [comment]
Just had another look at the cspell script in the package.json. Please remove the `--fail-fast` flag and add the `--gitignore` flag

**Comment by GCHQ-Developer-112** [comment]
Please can you also add the cspell script to the `canary-web-components` and `web-components` directories

**Comment by evenstensberg** [comment]
@GCHQ-Developer-112 fixed. The cspell script runs for all folders in `/packages/*`. When you run cspell you can see the directories getting linted.

**Comment by evenstensberg** [comment]
@GCHQ-Developer-112 I also recommend that you add the `quiet` flag in the CI. It will make the CI output less verbose and save you 💵. Since this is a gov project, I don't think that's necessary though.

**Comment by jd239** [comment]
There is some duplication with changed files between this PR and https://github.com/mi6/ic-ui-kit/pull/2236/files. Is a tidy up on the PR required? This will save time with reviewing the PR as the items in relation to the PR title can be reviewed instead of additional files like the CONTRIBUTING.md. Thanks.

**Comment by evenstensberg** [comment]
@jd239 Yea probably a bad branch update. I'll rebase and update the commits.

**Comment by evenstensberg** [comment]
PTAL @jd239

**Comment by evenstensberg** [comment]
https://github.com/mi6/ic-ui-kit/pull/2272 needs to merge before this PR is ready.

**Comment by evenstensberg** [comment]
PTAL @jd239

**Review by GCHQ-Developer-530 — APPROVED** [review]

**Review by GCHQ-Developer-112 — APPROVED** [review]

**Pull request merged**
