### PR TITLE
1970 more component playgrounds

### PR DESCRIPTION
**Pull request by GCHQ-Developer-530**
## Summary of the changes
Add playground story for link and skeleton

## Related issue
Part of #1970 

### General 

- [x] Changes to docs package checked and committed.
- [x] All acceptance criteria reviewed and met. 

### Testing

- [x] Relevant unit tests and visual regression tests added. 
- [x] Visual testing against Figma component specification completed. 

### Accessibility 

- [x] Accessibility Insights FastPass performed.
- [x] A11y unit test added and yields no issues.
- [x] A11y plug-in on Storybook yields no issues. 
- [x] Manual screen reader testing performed using NVDA and VoiceOver. 
- [x] Manual keyboard testing for keyboard controls and logical focus order. 
- [x] Correct roles used and ARIA attributes used correctly where required. 
- [x] Logical heading structure is maintained, and the HTML elements used for headings can be changed to fit within the wider page structure. 

### Resize/zoom behaviour 

- [x] Page can be zoomed to 400% with no loss of content. 
- [x] Screen magnifier used with no issues. 
- [x] Text resized to 200% with no loss of content.
- [x] Text spacing increased as per the [WCAG 1.4.12 success criterion](https://www.w3.org/TR/WCAG21/#text-spacing) with no loss of content.

### System modes

- [x] Browser setting 'prefers reduced motion' tested. No animations or motion visible whilst this setting is on. 
- [x] Windows High Contrast mode tested with no loss of content.
- [x] System light and dark mode tested with no loss of content.
- [x] Browser support tested (Chrome, Safari, Firefox and Edge). 

### Testing content extremes

- [x] Min/max content examples tested with no loss of content or overflow. 
- [x] All prop combinations work without issue. 
- [x] Tested for FOUC (Flash of Unstyled Content) in both SSR (Server-Side Rendering) and SSG (Static Site Generation) settings.
- [x] Controlled and uncontrolled input components tested.

### CODE REVIEW

**Review by ad9242 — CHANGES_REQUESTED** [review]
seem to be missing some props on link: `hreflang`, `rel`, `referrerpolicy`, `download`. would be good to add them, just to see how they are passed down to the native `<a>` tag under the covers

**Comment by GCHQ-Developer-530** [comment]
> seem to be missing some props on link: `hreflang`, `rel`, `referrerpolicy`, `download`. would be good to add them, just to see how they are passed down to the native `<a>` tag under the covers

I had considered these, when I added them they didn't change anything visually and especially download seemed like even the prop just being there meant that it was being applied (but I tested it and it works that way on the native `<a>` tag too) so couldn't test href or target if the link is downloaded even when download="false".

**Comment by ad9242** [comment]
> > seem to be missing some props on link: `hreflang`, `rel`, `referrerpolicy`, `download`. would be good to add them, just to see how they are passed down to the native `<a>` tag under the covers
> 
> I had considered these, when I added them they didn't change anything visually and especially download seemed like even the prop just being there meant that it was being applied (but I tested it and it seemed to work that way on the native `<a>` tag too) so couldn't test href or target if the link is downloaded even when download="false".

I think it would be good to add the download one. Looks like we could add 
`download={args.download === true}`
to only apply it, if true

**Comment by GCHQ-Developer-530** [comment]
> > > seem to be missing some props on link: `hreflang`, `rel`, `referrerpolicy`, `download`. would be good to add them, just to see how they are passed down to the native `<a>` tag under the covers
> > 
> > 
> > I had considered these, when I added them they didn't change anything visually and especially download seemed like even the prop just being there meant that it was being applied (but I tested it and it seemed to work that way on the native `<a>` tag too) so couldn't test href or target if the link is downloaded even when download="false".
> 
> I think it would be good to add the download one. Looks like we could add `download={args.download === true}` to only apply it, if true

I've fixed this for React but it still doesn't work for web components so I've created a ticket to investigate (https://github.com/mi6/ic-ui-kit/issues/2082) as I can't work out why it would work for one and not the other

**Review by GCHQ-Developer-847 — APPROVED** [review]

**Review by ad9242 — APPROVED** [review]

**Pull request merged**
