### PR TITLE
2934 add elements to end of cells in icdatatable

### PR DESCRIPTION
**Pull request by ec1467**
## Summary of the changes
Added action-element to ICDataTable cells that can be passed in through the data.

The action-element can be any HTMLElement, so a lot of the checklist would seem to not be applicable. Happy to help with any issues that arise and listen to any comments.

Storybook:
image

## Related issue
#2847
2934

### General 

- [ ] Changes to docs package checked and committed.
- [x] All acceptance criteria reviewed and met. 

### Testing

- [x] Relevant unit tests and visual regression tests added. 
- [ ] Visual testing against Figma component specification completed. 
- [x] Playground stories in React Storybook up to date, with any prop changes and additions addressed. 
- [x] Compare performance of modified components against develop using Performance addon in React Storybook.

### Accessibility 

- [x] Accessibility Insights FastPass performed.
- [x] A11y unit test added and yields no issues.
- [x] A11y plug-in on Storybook yields no issues. 
- [x] Manual screen reader testing performed using NVDA and VoiceOver. 
- [x] Manual keyboard testing for keyboard controls and logical focus order. 
- [x] Correct roles used and ARIA attributes used correctly where required. 
- [x] Logical heading structure is maintained, and the HTML elements used for headings can be changed to fit within the wider page structure. 

### Resize/zoom behaviour 

- [x] Page can be zoomed to 400% with no loss of content. 
- [x] Screen magnifier used with no issues. 
- [x] Text resized to 200% with no loss of content.
- [x] Text spacing increased as per the [WCAG 1.4.12 success criterion](https://www.w3.org/TR/WCAG21/#text-spacing) with no loss of content.

### System modes

- [x] Browser setting 'prefers reduced motion' tested. No animations or motion visible whilst this setting is on. 
- [x] Windows High Contrast mode tested with no loss of content.
- [x] System light and dark mode tested with no loss of content.
- [ ] Browser support tested (Chrome, Safari, Firefox and Edge). 

### Testing content extremes

- [x] Min/max content examples tested with no loss of content or overflow. 
- [x] All prop combinations work without issue. 
- [x] Tested for FOUC (Flash of Unstyled Content) in both SSR (Server-Side Rendering) and SSG (Static Site Generation) settings.
- [x] Controlled and uncontrolled input components tested.
- [x] Props/slots can be updated after initial render.

### CODE REVIEW

**Comment by ad9242** [comment]
Currently seems to be failing due to prettier errors. Please can you run `npm run prettier:fix` in the root directory & commit any changes it makes (squashing into the appropriate scope commits please)

**Comment by ad9242** [comment]
Please can you also ensure there is only 1 commit per scope eg, 1 for canary-web-components, 1 for canary-react?

**Comment by ad9242** [comment]
the audit issue on the repo should be resolved by #2918. please sync your fork & then rebase your branch off develop

**Comment by ec1467** [comment]
Commits are now squashed. Of the three tasks remaining: not sure what the first one is or if it's relevant? The second one, we don't have any specific Figma designs to compare with. Third one, it has been tested on Chrome and Firefox - currently unable to test on Safari or Edge.

Thanks for your help!

**Review by ad9242 — APPROVED** [review]

**Review by GCHQ-Developer-299 — APPROVED** [review]

**Pull request merged**
