### PR TITLE
chore(root): update github workflows to fix scorecard issues

### PR DESCRIPTION
**Pull request by GCHQ-Developer-530**
## Summary of the changes
Update github workflows to fix scorecard issues and remove scorecard badge from readme as we don't publish results so it won't ever have a valid repo url.

## Related issue
#1715 

### General 

- [x] Changes to docs package checked and committed.
- [x] All acceptance criteria reviewed and met. 

### Testing

- [x] Relevant unit tests and visual regression tests added. 
- [x] Visual testing against Figma component specification completed.

### Accessibility 

- [x] Accessibility Insights FastPass performed.
- [x] A11y unit test added and yields no issues.
- [x] A11y plug-in on Storybook yields no issues. 
- [x] Manual screen reader testing performed using NVDA and VoiceOver. 
- [x] Manual keyboard testing for keyboard controls and logical focus order. 
- [x] Correct roles used and ARIA attributes used correctly where required. 
- [x] Logical heading structure is maintained, and the HTML elements used for headings can be changed to fit within the wider page structure. 

### Resize/zoom behaviour 

- [x] Page can be zoomed to 400% with no loss of content. 
- [x] Screen magnifier used with no issues. 
- [x] Text resized to 200% with no loss of content.
- [x] Text spacing increased as per the [WCAG 1.4.12 success criterion](https://www.w3.org/TR/WCAG21/#text-spacing) with no loss of content.

### System modes

- [x] Browser setting 'prefers reduced motion' tested. No animations or motion visible whilst this setting is on. 
- [x] Windows High Contrast mode tested with no loss of content.
- [x] System light and dark mode tested with no loss of content.
- [x] Browser support tested (Chrome, Safari, Firefox and Edge). 

### Testing content extremes

- [x] Min/max content examples tested with no loss of content or overflow. 
- [x] All prop combinations work without issue. 
- [x] Tested for FOUC (Flash of Unstyled Content) in both SSR (Server-Side Rendering) and SSG (Static Site Generation) settings.

### CODE REVIEW

**Comment by GCHQ-Developer-112** [comment]
Does this mean we have to update the SHA every so often?

**Comment by GCHQ-Developer-530** [comment]
> Does this mean we have to update the SHA every so often?

We should only have to update them if we want to update the version, so pretty similar to the current implementation

**Review by GCHQ-Developer-112 — DISMISSED** [review]

**Comment by jd239** [comment]
Do the hashed version coincide with https://github.com/mi6/ic-ui-kit/pull/1761/files#diff-7950a4d9da07807ae6341f724c9d4d15f5c2e594bdc7d9865dd705bc4548b294?

**Comment by GCHQ-Developer-530** [comment]
> https://github.com/mi6/ic-ui-kit/pull/1761/files#diff-7950a4d9da07807ae6341f724c9d4d15f5c2e594bdc7d9865dd705bc4548b294

I don't think so as they're from the version tags, I'll update them

**Review by GCHQ-Developer-741 — APPROVED** [review]

**Review by GCHQ-Developer-741 — APPROVED** [review]

**Review by GCHQ-Developer-299 — APPROVED** [review]

**Pull request merged**
