### PR TITLE
fix(web-components): updated select searchable to update emitted events

### PR DESCRIPTION
**Pull request by jd239**
## Summary of the changes
Updated Searchable so the input value is not updated when highlighting options within the ic-menu. icOptionSelect and icChange are only emitted once the option and been selected. This update also allows the input value to be updated outside of input or menu selection.

Added onBlur to host close menu

PLEASE NOTE: The UX for Searchable select has slightly changed:
- Before: When highlighting menu options, the value in the input would reflect the highlighted option and trigger icChange.
- After: When highlighting menu options, the value in the input is no longer updated until `Enter` is pressed. `icChange` is emitted once the value is updated.

## Related issue
#525 

## Checklist
- [x] I have added relevant unit and visual regression tests.
- [ ] I have manually accessibility tested any changes, if relevant.
- [ ] I have ensured any changes match the Figma component library.

### CODE REVIEW

**Comment by ad9242** [comment]
Can we give each select in the stories a unique id to save having to reload the page each time you go to a new story? It seems to fail setting the options

**Comment by ad9242** [comment]
After selecting an option in a searchable select, then moving focus elsewhere, then come back, there is no longer a tick to show the selected option  - is that correct?

image

**Review by MI6-451 — DISMISSED** [review]

**Comment by GCHQ-Developer-741** [comment]
Another from the external filtering story:

1. Type a phrase so that it times out
2. Tab to the retry button
3. Click the retry button whilst it is focused
4. The menu closes

**Review by ad9242 — APPROVED** [review]

**Review by MI6-451 — APPROVED** [review]

**Review by GCHQ-Developer-741 — CHANGES_REQUESTED** [review]
Still getting the second issue I mentioned

**Review by GCHQ-Developer-741 — APPROVED** [review]

**Review by MI6-451 — APPROVED** [review]

**Review by ad9242 — DISMISSED** [review]

**Review by ad9242 — APPROVED** [review]

**Review by MI6-451 — APPROVED** [review]

**Pull request merged**
