### PR TITLE
feat(canary-web-components): allow specifying target for anchor in ic-data-table cell

### PR DESCRIPTION
**Pull request by irl**
## Summary of the changes

Allow specifying target and rel attributes for the anchor tag in the cell, along with the href. There are existing styles that add a new window icon to the link when the target is "_blank" and so no change is required to achieve that.

## Related issue
Closes: #2751

### General 

- [ ] Changes to docs package checked and committed.
- [x] All acceptance criteria reviewed and met. 

### Testing

- [ ] Relevant unit tests and visual regression tests added. 
- [ ] Visual testing against Figma component specification completed. 
- [ ] Playground stories in React Storybook up to date, with any prop changes and additions addressed. 
- [ ] Compare performance of modified components against develop using Performance addon in React Storybook.

### Accessibility 

- [ ] Accessibility Insights FastPass performed.
- [ ] A11y unit test added and yields no issues.
- [ ] A11y plug-in on Storybook yields no issues. 
- [ ] Manual screen reader testing performed using NVDA and VoiceOver. 
- [ ] Manual keyboard testing for keyboard controls and logical focus order. 
- [ ] Correct roles used and ARIA attributes used correctly where required. 
- [ ] Logical heading structure is maintained, and the HTML elements used for headings can be changed to fit within the wider page structure. 

### Resize/zoom behaviour 

- [ ] Page can be zoomed to 400% with no loss of content. 
- [ ] Screen magnifier used with no issues. 
- [ ] Text resized to 200% with no loss of content.
- [ ] Text spacing increased as per the [WCAG 1.4.12 success criterion](https://www.w3.org/TR/WCAG21/#text-spacing) with no loss of content.

### System modes

- [ ] Browser setting 'prefers reduced motion' tested. No animations or motion visible whilst this setting is on. 
- [ ] Windows High Contrast mode tested with no loss of content.
- [ ] System light and dark mode tested with no loss of content.
- [ ] Browser support tested (Chrome, Safari, Firefox and Edge). 

### Testing content extremes

- [ ] Min/max content examples tested with no loss of content or overflow. 
- [ ] All prop combinations work without issue. 
- [ ] Tested for FOUC (Flash of Unstyled Content) in both SSR (Server-Side Rendering) and SSG (Static Site Generation) settings.
- [ ] Controlled and uncontrolled input components tested.
- [ ] Props/slots can be updated after initial render.

### CODE REVIEW

**Review by GCHQ-Developer-112 — COMMENTED** [review]
Thank you for your contribution @irl! Please can you replicate the changes made in the canary-web-components storybook in the react storybook (in a separate commit)

**Comment by irl** [comment]
> Thank you for your contribution @irl! Please can you replicate the changes made in the canary-web-components storybook in the react storybook (in a separate commit)

Updating also required another change in canary-web-components for a file included in canary-react's storybook so I've added two new commits, one of which can be squashed into the previous before merging. I didn't know if you'd prefer me to force push the whole thing tidied up or leave it seperate so it's clearer for review.

**Comment by irl** [comment]
Ok, I guess I have to learn what a Cypress is. I'll work out how to fix those tests and follow up.

**Comment by GCHQ-Developer-112** [comment]
> Ok, I guess I have to learn what a Cypress is. I'll work out how to fix those tests and follow up.

No need to worry about the Cypress tests. We'll need to regenerate them on our end. They're failing because of the changes made to the `story-data.ts` file. The failing Cypress tests are visual regression tests that use the data from this file and so the changes mean the visual regression snapshots taken during the CI process no longer match the baseline snapshots.

**Comment by GCHQ-Developer-112** [comment]
> > Thank you for your contribution @irl! Please can you replicate the changes made in the canary-web-components storybook in the react storybook (in a separate commit)
> 
> Updating also required another change in canary-web-components for a file included in canary-react's storybook so I've added two new commits, one of which can be squashed into the previous before merging. I didn't know if you'd prefer me to force push the whole thing tidied up or leave it seperate so it's clearer for review.

Please do a fixup commit to merge the new canary-web-components commit into the first one. Please also change the type of commit for the canary-react commit to "feat" (feature) i.e. "feat(canary-react)..."

**Comment by ad9242** [comment]
Please can you rebase the branch off the latest develop?

**Comment by irl** [comment]
> Please can you rebase the branch off the latest develop?

That was not a fun rebase, but it is rebased.

**Comment by ad9242** [comment]
Thanks for that. It seems to be failing 3 cypress tests due to the open in new window now being there, To get this in, would you mind editing the icDataTable.cy.tsx file in the canary-react scope commit to skip those tests by changing the describe block to be:

describe.skip("IcDataTable row deletion", () => {

this will let it get through our ci tests & I will make a note to resolve once merged

**Comment by irl** [comment]
> Thanks for that. It seems to be failing 3 cypress tests due to the open in new window now being there, To get this in, would you mind editing the icDataTable.cy.tsx file in the canary-react scope commit to skip those tests by changing the describe block to be:
> 
> describe.skip("IcDataTable row deletion", () => {
> 
> this will let it get through our ci tests & I will make a note to resolve once merged

As a separate commit, or fixup the existing commit for canary-react?

**Comment by ad9242** [comment]
> > Thanks for that. It seems to be failing 3 cypress tests due to the open in new window now being there, To get this in, would you mind editing the icDataTable.cy.tsx file in the canary-react scope commit to skip those tests by changing the describe block to be:
> > describe.skip("IcDataTable row deletion", () => {
> > this will let it get through our ci tests & I will make a note to resolve once merged
> 
> As a separate commit, or fixup the existing commit for canary-react?

if you can fixup the existing please to keep 1 commit per scope

**Comment by irl** [comment]
Sorry, there were two blocks with failures, also "IcDataTable visual regression tests in high contrast mode"

**Review by ad9242 — APPROVED** [review]

**Review by gd2910 — APPROVED** [review]

**Pull request merged**
