### PR TITLE
fix(web-components): use safari fallback display

### PR DESCRIPTION
**Pull request by evenstensberg**
## Summary of the changes
Displays fallback value in safari (webkit)

## Related issue
[Tell us the issue number. If suggesting an improvement or component, please discuss it with us in an issue first.](https://github.com/mi6/ic-design-system/issues/961)

### General 

- [x] Changes to docs package checked and committed.
- [x] All acceptance criteria reviewed and met. 

### Testing

- [x] Relevant unit tests and visual regression tests added. 
- [x] Visual testing against Figma component specification completed. 
- [x] Playground stories in React Storybook up to date, with any prop changes and additions addressed. 
- [x] Compare performance of modified components against develop using Performance addon in React Storybook.

### Accessibility 

- [x] Accessibility Insights FastPass performed.
- [x] A11y unit test added and yields no issues.
- [x] A11y plug-in on Storybook yields no issues. 
- [x] Manual screen reader testing performed using NVDA and VoiceOver. 
- [x] Manual keyboard testing for keyboard controls and logical focus order. 
- [x] Correct roles used and ARIA attributes used correctly where required. 
- [x] Logical heading structure is maintained, and the HTML elements used for headings can be changed to fit within the wider page structure. 

### Resize/zoom behaviour 

- [x] Page can be zoomed to 400% with no loss of content. 
- [x] Screen magnifier used with no issues. 
- [x] Text resized to 200% with no loss of content.
- [x] Text spacing increased as per the [WCAG 1.4.12 success criterion](https://www.w3.org/TR/WCAG21/#text-spacing) with no loss of content.

### System modes

- [x] Browser setting 'prefers reduced motion' tested. No animations or motion visible whilst this setting is on. 
- [x] Windows High Contrast mode tested with no loss of content.
- [x] System light and dark mode tested with no loss of content.
- [x] Browser support tested (Chrome, Safari, Firefox and Edge). 

### Testing content extremes

- [x] Min/max content examples tested with no loss of content or overflow. 
- [x] All prop combinations work without issue. 
- [x] Tested for FOUC (Flash of Unstyled Content) in both SSR (Server-Side Rendering) and SSG (Static Site Generation) settings.
- [x] Controlled and uncontrolled input components tested.

### CODE REVIEW

**Comment by evenstensberg** [comment]
@ad9242 In which selectors do you want the fallback statement? 

It seems that you were aware that layouts in webkit needs a fallback value, so that's good.

Screenshot 2024-07-25 at 11 49 27

**Comment by GCHQ-Developer-530** [comment]
> @ad9242 In which selectors do you want the fallback statement?
> 
> It seems that you were aware that layouts in webkit needs a fallback value, so that's good.
> 
> Screenshot 2024-07-25 at 11 49 27

`display: -webkit-box;` should be added for all sizes of icon button. In this PR currently it's only added for large icon buttons.

**Comment by evenstensberg** [comment]
Please do test this manually in safari locally for ic-design-website. Preferably on different viewports.

**Comment by evenstensberg** [comment]
Closing this, because the approach is flawed. There's a problem with the parent of a button, which affects the icons.

**Pull request closed without merging**
